### ISSUE TITLE
How to specify multiple testproject 

### ISSUE THREAD

**Issue by Tirthas** [b3b00/coverlet-action#19]
Can i do something like this:

- name : coverlet
uses: b3b00/coverlet-action@1.2.5
with:
  testProject: ['myProjectTests/myProjectTests1.csproj', 'myProjectTests/myProjectTests2.csproj']
  output: 'lcov.info'
  outputFormat: 'lcov'
  excludes: '[program]*,[test]test.*'
- name: coveralls      
uses: coverallsapp/github-action@v1.1.1
with:

**Comment by b3b00** [comment]
Hello @Tirthas , I think simple listing csproj separated by spaces should do the job.

Coule you try and share please

**Comment by b3b00** [comment]
@Tirthas , please answer ! you've opened and immediatly closed an issue. Have you find a way to solve your need ? share it with the community ! it's the way OSS works

**Comment by b3b00** [comment]
As for now multiple test project are not supported. 
Specifying many test project in the testProject attribute does not work. specifying the sln solution file would run all the tests but then will generate as many coverage report as test project.
We need some rework to be able to merge those report in a single one.

**Comment by b3b00** [comment]
@Tirthas ,

version 1.3.4 solves the issue. Using the sln as test project coverlet-action will run all test project included in solution and aggregate coverage.
Warning : coverage threshold will not be tested as coverlet output many coverage table that can not be merged to get a global coverage. i will look if something is possible here.

```yaml
    - name: Test with dotnet
      uses: b3b00/coverlet-action@1.3.4
      id: 'coverlet'
      with:
        testProject: solution.sln
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*'
```
