### ISSUE TITLE
OpenCover output file being ignored

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#23]
This cropped up in the last couple of days.

https://github.com/Sauceforge/Saucery/actions/runs/14878662776/job/41781310993

And yet the file exists in the directory it said it couldn't find it:

![Image](https://github.com/user-attachments/assets/8b5b940d-e59c-4772-94b0-24e288b5eb2a)

Um, I'm confused as to what broke.

**Comment by olduh29** [comment]
Hello @agray , looking at your workflow I see that you use b3b00/ceverlet-action@11.9
That's quite an old version . Could you try the last version 1.3.4 and see if it solves, please ?

**Comment by agray** [comment]
ok. looks like 1.3.1 is the latest published versions. Tried that.

https://github.com/Sauceforge/Saucery/actions/runs/14884559022/job/41800573696

different error.

**Comment by agray** [comment]
With version 1.3.4, no files seem to be produced:

https://github.com/Sauceforge/Saucery/actions/runs/14904722638

**Comment by b3b00** [comment]
I think I've got it. you're expecting the coverage file to be at the UT project level ( `.Saucery.Core.Tests/TestResults` ) but coverlet-action produces it at `./TestResults` (at the current dir level , so the root of the repo). 
The `coverageFile` output variable of the coverlet-action gives you the absolute path to the coverage file. I don't completely understand how is built your pipeline so I don't know if it would be easy to use this output variable

**Comment by agray** [comment]
> I think I've got it. you're expecting the coverage file to be at the UT project level ( `.Saucery.Core.Tests/TestResults` ) but coverlet-action produces it at `./TestResults` (at the current dir level , so the root of the repo). The `coverageFile` output variable of the coverlet-action gives you the absolute path to the coverage file. I don't completely understand how is built your pipeline so I don't know if it would be easy to use this output variable

UnitTests themselves (`UNIT_COVERAGE_FILENAME`) I expect to be at `Saucery.Core.Tests/opencover.nunit.integration.xml`
NUnit Integration Tests (`NUNIT_INTEGRATION_COVERAGE_FILENAME`) at `Merlin.NUnit/opencover.nunit.integration.xml`
XUnit Integration Tests (`XUNIT_INTEGRATION_COVERAGE_FILENAME`) at `Merlin.XUnit/opencover.xunit.integration.xml`

and so on. This has worked correctly for a long time.

Has that behaviour changed since v11.9. As it has worked for a long time and I haven't needed to change paths. Does the new version insert a `/TestResults/` directory in the path before `output` directive?

My master branch is using v11.9 and the pathing is not a problem.

**Comment by agray** [comment]
why does this work?

```

**Comment by agray** [comment]
Why does this work?

```
- name: Run Unit Tests
  uses: b3b00/coverlet-action@1.3.5-alpha1
  with:
    testProject: ${{ env.UT_PROJECT }}
    output: ${{ env.UNIT_COVERAGE_FILENAME }}
    outputFormat: ${{ env.COVERAGE_FORMAT }}
    threshold: ${{ env.COVERAGE_THRESHOLD }}
    excludes: '[Saucery.Core.Tests]Tests.*,[Saucery]AutoGeneratedProgram,[Saucery]Saucery.Selenium.*,[Saucery]Saucery.Driver.SauceryAndroid*,[Saucery]Saucery.Driver.SauceryIOS*,[Saucery]Saucery.Tests.SauceryAndroid*,[Saucery]Saucery.Tests.SauceryIOS*,[Saucery]Saucery.DataSources.EnvCompositor*,[Saucery]Saucery.Util.WebControl'
```

as seen here: https://github.com/Sauceforge/Saucery/actions/runs/14940364082/job/41976400496

but these don't:
```
- name: Run TUnit Integration Tests
  uses: b3b00/coverlet-action@1.3.5-alpha1
  with:
    testProject: ${{ env.M_TUNIT_PROJECT }}
    output: ${{ env.TUNIT_INTEGRATION_COVERAGE_FILENAME }}
    outputFormat: ${{ env.COVERAGE_FORMAT }}
    threshold: ${{ env.COVERAGE_THRESHOLD }}
    excludes: '[Saucery.Core.Tests]Tests.*,[Saucery]AutoGeneratedProgram,[Saucery]Saucery.Selenium.*,[Saucery]Saucery.Driver.SauceryAndroid*,[Saucery]Saucery.Driver.SauceryIOS*,[Saucery]Saucery.Tests.SauceryAndroid*,[Saucery]Saucery.Tests.SauceryIOS*,[Saucery]Saucery.DataSources.EnvCompositor*,[Saucery]Saucery.Util.WebControl'
```

```
- name: Run TUnit Real Integration Tests
  uses: b3b00/coverlet-action@1.3.5-alpha1
  with:
    testProject: ${{ env.M_RD_TUNIT_PROJECT }}
    output: ${{ env.TUNIT_RD_INTEGRATION_COVERAGE_FILENAME }}
    outputFormat: ${{ env.COVERAGE_FORMAT }}
    threshold: ${{ env.COVERAGE_THRESHOLD }}
    excludes: '[Saucery.Core.Tests]Tests.*,[Saucery]AutoGeneratedProgram,[Saucery]Saucery.Selenium.*,[Saucery]Saucery.Driver.SauceryAndroid*,[Saucery]Saucery.Driver.SauceryIOS*,[Saucery]Saucery.Tests.SauceryAndroid*,[Saucery]Saucery.Tests.SauceryIOS*,[Saucery]Saucery.DataSources.EnvCompositor*,[Saucery]Saucery.Util.WebControl'
```

as seen here: 
https://github.com/Sauceforge/Saucery/actions/runs/14940364082/job/41976425983 
and here:
https://github.com/Sauceforge/Saucery/actions/runs/14940364082/job/41976425980 

I don't see the difference.
