### ISSUE TITLE
Coverage Output File Needs to exist?

### ISSUE THREAD

**Issue by agray** [b3b00/coverlet-action#6]
I have this in pipeline.yml file:

```
- name: Run Unit Tests
  uses: b3b00/coverlet-action@1.1.1
    with:
      testProject: ${{ env.UT_PROJECTDIR }}
      output: 'opencover.info'
      outputFormat: 'opencover'
      excludes: '[program]*,[UnitTests]Tests.*,[Merlin]*'
```
env.UT_PROJECTDIR is defined as:

`UT_PROJECTDIR: UnitTests\\                      # unit test directory`

The output I get is:

> Run b3b00/coverlet-action@1.1.1
create coverlet args
found exclusions [program]*,[UnitTests]Tests.*,[Merlin]*
coverlet args -p:coverletOutput=opencover.info -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude=\"[program]*,[UnitTests]Tests.*,[Merlin]*\" UnitTests\\
run dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Saucery -> /home/runner/work/Saucery/Saucery/Saucery/bin/Debug/net5.0/Saucery.dll
  UnitTests -> /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll
Test run for /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

> Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped FlowControlTest [< 1 ms]

> Passed!  - Failed:     0, Passed:    41, Skipped:     1, Total:    42, Duration: 829 ms - /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll (net5.0)

> Error: error occured : coverage file not found at ./opencover.info
[1]covergae file not found at ./opencover.info
setting output coverageFile : >>./opencover.info<<
coverlet test done.

I interpret the error message as requiring the output file to exist !?  I would have expected this output file to be WRITTEN by the action and it SHOULDN'T exist.

This doesn't seem right.  What am I missing? Must be something silly on my part.

Thanks in advance.

**Comment by b3b00** [comment]
hello @agray , output file is not required to exist. I think the problem is witn the testprohect arg of the action. it needs to be the path to the unit test csproj file. in your case it only contains the directory name. 
it should be somethin like 
```
-testproject: UnitTests/UnitTests.csproj

hopes this will help
```

**Comment by agray** [comment]
Thank you.  I found I also made the mistake of thinking the agent was windows rather than unix.  Once the directory separator was corrected to '/' it executed the unit tests and emitted the coverage output file.

Question: Does the action currently support making a quality decision on the level of coverage and fail the build if deemed too low?

**Comment by agray** [comment]
Unfortunately it still fails:

```
- name: Run Unit Tests
  uses: b3b00/coverlet-action@1.1.1
    with:
      testProject: ${{ env.UT_PROJECT }}
      output: 'opencover.info'
      outputFormat: 'opencover'
      excludes: '[program]*,[UnitTests]Tests.*,[Merlin]*'
```

env.UT_PROJECT is defined as:

`UT_PROJECT: UnitTests/UnitTests.csproj # unit test directory`

And my output is:

> Run b3b00/coverlet-action@1.1.1
> create coverlet args
> found exclusions [program]*,[UnitTests]Tests.*,[Merlin]*
> coverlet args -p:coverletOutput=opencover.info -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude=\"[program]*,[UnitTests]Tests.*,[Merlin]*\" UnitTests/UnitTests.csproj
> run dotnet test
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   Saucery -> /home/runner/work/Saucery/Saucery/Saucery/bin/Debug/net5.0/Saucery.dll
>   UnitTests -> /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll
> Test run for /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll (.NETCoreApp,Version=v5.0)
> Microsoft (R) Test Execution Command Line Tool Version 16.11.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.
>   Skipped FlowControlTest [< 1 ms]
> 
> Passed!  - Failed:     0, Passed:    41, Skipped:     1, Total:    42, Duration: 818 ms - /home/runner/work/Saucery/Saucery/UnitTests/bin/Debug/net5.0/UnitTests.dll (net5.0)
> 
> Error: error occured : coverage file not found at UnitTests/opencover.info
> [1]covergae file not found at UnitTests/opencover.info
> setting output coverageFile : >>UnitTests/opencover.info<<
> coverlet test done.
